services:
  chitchat.webapi:
    image: ${DOCKER_REGISTRY-}chitchatwebapi
    build:
      context: ../../
      dockerfile: src/ChitChat.WebAPI/Dockerfile
    ports:
      - "80:8080"
      - "443:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/chitchat.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=chitchat
    env_file:
      - ../../src/ChitChat.WebAPI/.env
    networks:
      - productnetwork
    restart: unless-stopped

networks:
  productnetwork:
