global using ChitChat.Domain.Entities;
global using ChitChat.Domain.Entities.PostEntities;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using ChitChat.Domain.Enums;
global using ChitChat.Domain.Identity;
